### ISSUE TITLE
No change with plugin

### ISSUE THREAD

**Issue by theorganicon** [kasparsd/minit#37] opened 2015-01-18 02:01 UTC
Hello,

Upon activating the plugin, Google Page Speed Test continues to give this alert: "Eliminate render-blocking JavaScript and CSS in above-the-fold content."  Please advise.

Also, how does one keep the plugin updated, once installed?

Thank you very much for your plugin and endeavors.

**Comment by santo007** [comment] 2015-01-23 14:42
Hello @theorganicon the suggestion and solution for <strong>Eliminate render-blocking JavaScript and CSS in above-the-fold content.</strong> is the following
What it is ?
The problem is that js are loading below body tag which makes the page much time to load.Therefore you need to move your js after body tag
<strong>Solution</strong><br/>
Just add the following script to functions.php which is located in your themes folder
<pre><code>function footer_enqueue_scripts() {
   remove_action('wp_head', 'wp_print_scripts');
    remove_action('wp_head', 'wp_print_head_scripts', 9);
    remove_action('wp_head', 'wp_enqueue_scripts', 1);
    add_action('wp_footer', 'wp_print_scripts', 5);
    add_action('wp_footer', 'wp_enqueue_scripts', 5);
    add_action('wp_footer', 'wp_print_head_scripts', 5);
}
add_action('after_setup_theme', 'footer_enqueue_scripts');</code></pre>

**Comment by theorganicon** [comment] 2015-01-23 14:53
Thank you so much.  If it still does not work for my particular site when I reinstall the plugin, should the code remain?  Will it interfere with other plugin code?

**Comment by santo007** [comment] 2015-01-23 15:04
@theorganicon Minit just combines css and js(IF you are not developer or you dont know any programming language just skip to solution)<br />
For example if i have 5 css and js files.It is easier to make a single http request rather than making 5 requests(here request refers to downloading the css and js files which are optimized on browser side)<br/>
This is what minit plugin does<br/>
It doesnt make all pagespeed optimisations<br/>
 <strong>solution<br/></strong>
Since you are adding the provided code on functions.php which is located in your themes folder the code remains even though you reinstall the plugin.

**Comment by theorganicon** [comment] 2015-01-23 16:11
Thank you so much. We shall give this a try!

**Comment by kasparsd** [comment] 2016-01-03 14:18
Closing because not really an issue with the plugin.

**Closed by kasparsd** 2016-01-03 14:18 UTC
